title: Configuration
data:
  copyright_since: 2017
  privacy_statement_type: entry
  privacy_statement_entry: 8994808d-fbd1-41bf-bd07-26b6b5782fee
  404_title: 'Pagina niet gevonden'
  404_text: 'De pagina waar je naar zocht is helaas niet (meer) beschikbaar.'
