error_404_entry: ffa6e260-6f3b-4dca-9de5-1d05bf5c3b43
phone: '+31 6 28 42 38 42'
email: info@studio1902.nl
contact_page: 4fbf1889-af9d-4852-8339-555bebbcc803
availability_from: '2022-08-01'
copyright_since: 2017
privacy_statement_type: entry
privacy_statement_entry: 8994808d-fbd1-41bf-bd07-26b6b5782fee
footer_animations:
  -
    animation: cat.json
    text: 'Looking for a cat person Statamic Developer for your next project?'
    audio: cat-purring.mp3
  -
    animation: knive.json
    text: 'Got the ingredients, but looking for a chef? Let''s discuss the menu!'
    audio: chopping-veggies.mp3
  -
    animation: nonuclear.json
    text: 'Working on a brighter future as well? Your new website can help.'
    audio: nature.mp3
  -
    animation: fire.json
    text: 'Looking for a hot new website? Let''s start a fire.'
    audio: fire-burning.mp3
