title: Services
sites:
  - nl
  - en
propagate: false
template: services/show
layout: layout
revisions: false
route: '{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 1
