title: Services
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          input_type: text
          localizable: true
          listable: true
          display: Title
          validate:
            - required
      -
        handle: teaser
        field: common.text_plain
        config:
          localizable: true
          display: Teaser
          validate: required
      -
        import: page_builder
  seo:
    display: SEO
    fields:
      -
        import: seo
  sidebar:
    display: Sidebar
    fields:
      -
        handle: meta
        field:
          type: section
          instructions: 'This entry''s meta data.'
          display: Meta
      -
        handle: slug
        field:
          type: slug
          localizable: true
          generate: true
          listable: hidden
          display: Slug
          validate:
            - required
      -
        handle: footer_animation
        field: common.entry
        config:
          display: 'Footer animation'
          instructions: 'Falls back to a random footer animation.'
          collections:
            - footer_animations
